trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: DownloadSecureFile@1
  name: APIKEY
  inputs:
    secureFile: 'APIKEY'

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Agent.TempDirectory)
    contents: '**/APIKEY'
    targetFolder: $(Build.SourcesDirectory)/OurStory.Sync.Lib/APIKEY

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    configuration: 'Mac'
