trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    configuration: 'Mac'
