version: "2"

volumes:
  mongo-data:
    external: false
  redis-data:
    external: false

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./server.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./bootlegger.conf:/etc/nginx/vhost.d/default:ro"
      - "/usr/share/nginx/html"
      - "./upload:/usr/src/app/upload"
    volumes_from:
      - web

  redis:
    restart: always
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  mongo:
    restart: always
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  beanstalk:
    restart: always
    image: kusmierz/beanstalkd

  worker:
    image: bootlegger/transcode-server:latest
    restart: always
    volumes_from:
      - web
    environment:
      - MYIP=10.10.10.1
    volumes:
      - "./worker.js:/usr/src/app/config/local.js:ro"
      - "./upload:/usr/src/app/upload"
      - "/.tmp/"

  web:
    restart: always
    image: bootlegger/server-app:latest
    depends_on: 
      - redis
      - mongo
      - beanstalk
    expose:
      - 1337
    volumes:
      - "./config.js:/usr/src/app/config/local.js:ro"
      - "./upload:/usr/src/app/upload"
    environment:
      - MYIP=10.10.10.1